### ISSUE TITLE
When attempting to install the Catalyze CLI /2.1.1/catalyze_2.1.1_i386.deb onto an Ubuntu 14.10 Utopic machine the Ubuntu Software Center rejects the package installation

### ISSUE THREAD

**Issue by ctkdev** [catalyzeio/cli#1]
When attempting to install the Catalyze CLI /2.1.1/catalyze_2.1.1_i386.deb onto an Ubuntu 14.10 Utopic machine the Ubuntu Software Center rejects the package installation with the following error 

"The package doesn't provide a valid Installed-Size control field. See Debian Policy 5.6.20." 

Source https://www.debian.org/doc/debian-policy/ch-controlfields.html

__5.6.20 Installed-Size__

This field appears in the control files of binary packages, and in the Packages files. It gives an estimate of the total amount of disk space required to install the named package. Actual installed size may vary based on block size, file system properties, or actions taken by package maintainer scripts.

The disk space is given as the integer value of the estimated installed size in bytes, divided by 1024 and rounded up.

__Screenshot__

![ubuntu software center_054](https://cloud.githubusercontent.com/assets/910247/9935972/c696fa0a-5d27-11e5-98a3-63125e93aab1.png)

**Comment by jault3** [comment]
Hi @ctkdev, this should be fixed with version 3.0.0 and above.

**Comment by ctkdev** [comment]
I will install the new CLI and confirm. Thank you!
