### ISSUE TITLE
Windows CLI Username/Password Not Working

### ISSUE THREAD

**Issue by andrewawagner** [catalyzeio/cli#18]
If username/password is saved in an environment variable in the Windows CLI, the `catalyze associate` command starts executing correctly but then exists with the error message:

'Exec: "sh": executable file not found in %PATH%'

Edit: Below was not in command prompt, strike that out.

~~If I did not use an environment variable but waited for the prompt, I input my username and then the password prompt immediately flashed past not allowing me to input anything.~~

This was an issue for 32-bit Windows 7 and 32-bit client. Going to test with 64-bit shortly.

**Comment by jault3** [comment]
@andrewawagner when you **did not** use an environment variable, did you use the default command prompt on windows or did you use another shell?

**Comment by andrewawagner** [comment]
On 64-bit Windows 10 with the 64-bit client, the `catalyze associate` command returned properly using environment variables.

**Comment by andrewawagner** [comment]
On 64-bit Windows 10 with the 64-bit client, the `catalyze associate` command did not work when using the prompts to input username/password. This is using the standard CMD shell.

**Comment by jault3** [comment]
Fixed via #16
