### ISSUE TITLE
Backup before Imports

### ISSUE THREAD

**Issue by skarlupka** [catalyzeio/cli#3]
We should initiate a backup of a customer's database before their sql file gets imported via the  `catalyze db import` command.  This will allow a path for engineers to recover a very recent previous version of the database if there are issues.

**Comment by derekrockwell** [comment]
+1

**Comment by jault3** [comment]
Fixed via 7021c0eaad241bfee5b8f12354b60ab20a8f6577 (version 2.1.5)
